name: deployment

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install pypa/build
        run: python -m pip install --upgrade pip build

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir=dist/ .

      - name: Publish distribution 📦
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Login to Docker Hub
        id: login-dockerhub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38

      - name: Build, tag, and push image to Docker Hub
        id: build-image
        context: .
        env:
          DOCKERHUB_NAMESPACE: ${{ steps.login-dockerhub.outputs.registry }}
          IMAGE_TAG: ${{ steps.meta.outputs.tags }}
        run: |
          # Build a docker container and push it to Docker Hub
          docker build -t $DOCKERHUB_NAMESPACE/timezone-converter:$IMAGE_TAG .
          docker push $DOCKERHUB_NAMESPACE/timezone-converter:$IMAGE_TAG
          echo "::set-output name=image::$DOCKERHUB_NAMESPACE/timezone-converter:$IMAGE_TAG"
      

